# Generated by Django 2.1 on 2018-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=96)),
                ('secret_key', models.CharField(max_length=96)),
            ],
        ),
    ]
