# Generated by Django 2.1 on 2018-08-22 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=256)),
                ('kind', models.CharField(default='MODULEAPI', max_length=50)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('raw_stdout', models.TextField(default='')),
                ('json_args', models.TextField(default='{}')),
                ('status', models.CharField(max_length=50)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', related_query_name='history', to='api.Projects')),
            ],
            options={
                'ordering': ['-id'],
                'default_related_name': 'history',
            },
        ),
        migrations.AlterIndexTogether(
            name='history',
            index_together={('id', 'project', 'module', 'status', 'start_time', 'stop_time')},
        ),
    ]
